package com.go_game.client;

public enum RegisterStatusEnum { 
    SUCCESSFUL,
    LOGIN_ALREADY_EXISTS,
    PASSWORD_TOO_SHORT,
    PASSWORD_TOO_LONG,
    PASSWORD_NOT_SATISFYING_REQUIREMENTS,
    CONNECTION_ERROR,
    LOGIN_TO_LONG
}
