name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and Test shared
      run: mvn -B clean install test --file shared/pom.xml

    - name: Build and Test go_server
      run: mvn -B clean install test --file go_server/pom.xml

    - name: Build and Test go_client
      run: mvn -B clean install test --file go_client/pom.xml

